import Vue from 'vue'
import { Button, Form, FormItem, Input ,Message, Container, Header, Aside, Main, Menu, Submenu,
 MenuItemGroup, MenuItem, Breadcrumb, BreadcrumbItem, Card, Dialog,Row, Col,
 TimePicker,Option,Select,InputNumber,Checkbox,Table,TableColumn,Tooltip,Tabs,TabPane,Pagination} from 'element-ui'

Vue.use(Button)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Container)
Vue.use(Header)
Vue.use(Aside)
Vue.use(Main)
Vue.use(Menu)
Vue.use(MenuItemGroup)
Vue.use(Submenu)
Vue.use(MenuItem)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Card)
Vue.use(Dialog)
Vue.use(Row)
Vue.use(Col)
Vue.use(TimePicker)
Vue.use(Option)
Vue.use(Select)
Vue.use(InputNumber)
Vue.use(Checkbox)
Vue.use(TableColumn)
Vue.use(Table)
Vue.use(Tooltip)
Vue.use(Tabs)
Vue.use(TabPane)
Vue.use(Pagination)
Vue.prototype.$message = Message
